FROM ruby:3.3-slim

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev libyaml-dev libxml2-dev libxslt-dev postgresql-client curl && rm -rf /var/lib/apt/lists/*

RUN apt-get update -qq && apt-get install -y --no-install-recommends \
    chromium \
    chromium-driver \
    fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-freefont-ttf libxss1 \
    && rm -rf /var/lib/apt/lists/*
RUN ln -sf /usr/bin/chromium /usr/bin/google-chrome

WORKDIR /app

COPY Gemfile Gemfile.lock* ./
RUN bundle install

COPY . .

EXPOSE 3000
CMD ["bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]
